In [1]:
import pandas as pd
import random
import csv

In [2]:
filename = 'C:/Users/bhayek/Desktop/_t/NPI Data/NPPES_Data_Dissemination_April_2018/npidata_pfile_20050523-20180408.csv'

In [3]:
# Get the number of rows in the source file
row_count = sum(1 for row in open(filename, errors='ignore'))
print('Number of rows: {}'.format(row_count))

Number of rows: 5546686

In [4]:
# Reduce size option 1: Create a new file with sampled rows
samplesize = 100
skiprows = sorted(random.sample(range(1, row_count), row_count-samplesize))
df_sample = pd.read_csv(filename, skiprows=skiprows, dtype=str)
df_sample = df_sample.fillna('')
df_sample.head(5)

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,...,Healthcare Provider Taxonomy Group_6,Healthcare Provider Taxonomy Group_7,Healthcare Provider Taxonomy Group_8,Healthcare Provider Taxonomy Group_9,Healthcare Provider Taxonomy Group_10,Healthcare Provider Taxonomy Group_11,Healthcare Provider Taxonomy Group_12,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15
0,1326041740,1,,,,REILLY,GERARD,P,DR.,,...,,,,,,,,,,
1,1871590117,1,,,,JERNBERG,EMILY,RUTH,DR.,,...,,,,,,,,,,
2,1245224708,1,,,,GOVER,DAVID,DEAN,DR.,,...,,,,,,,,,,
3,1548257223,2,,<UNAVAIL>,"SHEA CENTER FOR EARS, HEARING AND BALANCE INC.",,,,,,...,,,,,,,,,,
4,1417931973,2,,<UNAVAIL>,"NORTHSIDE HOSPITAL, INC.",,,,,,...,,,,,,,,,,

In [5]:
filetrim = 'C:/Users/bhayek/Desktop/_t/NPI Data/NPPES_Data_Dissemination_April_2018/npidata_pfile_20050523-20180408_trim.csv'

In [6]:
# Reduce size option 2: Create a new file with just the columns we want
chunksize = 10**5
cols_to_keep = ['NPI', 'Entity Type Code', 'Replacement NPI', 'Employer Identification Number (EIN)', 
                'Provider Organization Name (Legal Business Name)', 'Provider Last Name (Legal Name)', 
                'Provider First Name', 'Provider Middle Name', 'Provider Name Prefix Text', 'Provider Name Suffix Text', 
                'Provider Credential Text', 'Provider Other Organization Name', 'Provider Other Organization Name Type Code', 
                'Last Update Date', 'NPI Deactivation Reason Code', 'NPI Deactivation Date', 'NPI Reactivation Date']

header = True
for chunk in pd.read_csv(filename, chunksize=chunksize, usecols=cols_to_keep, dtype=str):
    chunk.to_csv(filetrim, mode='a', index=False, header=header)
    # Only write the header once
    header = False

In [7]:
# Count the rows in the new file
row_count = sum(1 for row in open(filetrim, errors='ignore'))
print('Number of rows: {}'.format(row_count))

Number of rows: 5546686

In [8]:
# Load the file for use
df_npi_trim = pd.read_csv(filetrim, dtype=str)
df_npi_trim = df_npi_trim.fillna('')
df_npi_trim.head(5)

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider Other Organization Name,Provider Other Organization Name Type Code,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date
0,1679576722,1,,,,WIEBE,DAVID,A,,,M.D.,,,07/08/2007,,,
1,1588667638,1,,,,PILCHER,WILLIAM,C,DR.,,MD,,,05/29/2014,,,
2,1497758544,2,,<UNAVAIL>,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",,,,,,,CAPE FEAR VALLEY HOME HEALTH AND HOSPICE,3,09/26/2011,,,
3,1306849450,1,,,,SMITSON,HAROLD,LEROY,DR.,II,M.D.,,,01/03/2008,,,
4,1215930367,1,,,,GRESSOT,LAURENT,,DR.,,M.D.,,,11/25/2014,,,

In [9]:
# Basic sanity check on uniqueness of NPIs
print('Total rows: {}'.format(len(df_npi_trim['NPI'])))
print('Unique NPIs: {}'.format(len(df_npi_trim['NPI'].unique())))

Total rows: 5546685
Unique NPIs: 5546685

In [10]:
# Breakdown of individuals vs organizations
print('Number of individual providers: {}'.format(len(df_npi_trim[df_npi_trim['Entity Type Code'] == '1'])))
print('Number of organizations: {}'.format(len(df_npi_trim[df_npi_trim['Entity Type Code'] == '2'])))

Number of individual providers: 4155027
Number of organizations: 1269694

In [11]:
# Check the difference between total rows + providers / organizations
df_npi_trim[(df_npi_trim['Entity Type Code'] != '1') & (df_npi_trim['Entity Type Code'] != '2')].head(5)

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider Other Organization Name,Provider Other Organization Name Type Code,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date
35,1891798849,,,,,,,,,,,,,,,11/13/2017,
52,1770586729,,,,,,,,,,,,,,,08/03/2017,
110,1427051457,,,,,,,,,,,,,,,07/08/2014,
141,1730182783,,,,,,,,,,,,,,,06/19/2007,
142,1649273699,,,,,,,,,,,,,,,02/12/2016,